name: bennu_client
description: Aplicação cliente do Bennu para Android e Windows.
publish_to: "none"
version: 0.6.7+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.0

flutter:
  uses-material-design: true
