import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:http/http.dart' as http;
import 'package:shared_preferences/shared_preferences.dart';

const bg=Color(0xFF070A0F),panel=Color(0xFF10151D),muted=Color(0xFF8B98A8),green=Color(0xFF48E08A),orange=Color(0xFFFF7043);
void main()=>runApp(const BennuApp());
class BennuApp extends StatelessWidget{const BennuApp({super.key});Widget build(BuildContext c)=>MaterialApp(title:'Bennu OS',debugShowCheckedModeBanner:false,locale:const Locale('pt','PT'),supportedLocales:const[Locale('pt','PT'),Locale('en','US')],localizationsDelegates:GlobalMaterialLocalizations.delegates,theme:ThemeData(useMaterial3:true,brightness:Brightness.dark,scaffoldBackgroundColor:bg,colorScheme:ColorScheme.fromSeed(seedColor:orange,brightness:Brightness.dark),cardTheme:CardThemeData(color:panel,elevation:0,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(18)))),home:const Home());}
class Api{final String base;Api(this.base);Future<Map<String,dynamic>> get(String p)async{if(base.isEmpty)throw Exception('Servidor não configurado');final r=await http.get(Uri.parse('${base.replaceFirst(RegExp(r'/+$'),'')}$p')).timeout(const Duration(seconds:8));if(r.statusCode!=200)throw Exception('HTTP ${r.statusCode}');return jsonDecode(r.body);}}
class Home extends StatefulWidget{const Home({super.key});State<Home> createState()=>_Home();}
class _Home extends State<Home>{String server='';Map<String,dynamic>? data;String? error;bool busy=false;int tab=0;final url=TextEditingController();
 static const names=['Centro','Agentes','Missões','Segurança','Analytics','Cloud','Business','Vendas','Terminal','Definições'];
 void initState(){super.initState();load();}Future<void>load()async{final p=await SharedPreferences.getInstance();server=p.getString('bennu_api_url')??'';url.text=server;if(server.isNotEmpty)refresh();if(mounted)setState((){});}
 Future<void>refresh()async{setState(()=>busy=true);try{final d=await Api(server).get('/api/v1/mobile/operations');if(mounted)setState(()=>{data=d,error=null});}catch(e){if(mounted)setState(()=>error=e.toString().replaceFirst('Exception: ',''));}finally{if(mounted)setState(()=>busy=false);}}
 Future<void>save()async{final v=url.text.trim().replaceFirst(RegExp(r'/+$'),'');final p=await SharedPreferences.getInstance();await p.setString('bennu_api_url',v);setState(()=>server=v);await refresh();}
 Widget page(){if(tab==9)return settings();if(tab==1)return agents();if(tab==2)return missions();if(tab==3)return security();if(tab==4)return analytics();return dashboard();}
 Widget shell(Widget child)=>SafeArea(child:SingleChildScrollView(padding:const EdgeInsets.all(20),child:child));
 Widget dashboard(){final online=data!=null&&error==null;final ev=(data?['events'] as List? ?? const[]);return shell(Column(crossAxisAlignment:CrossAxisAlignment.start,children:[hero(online),const SizedBox(height:14),if(error!=null)info(Icons.warning_amber_rounded,'Servidor indisponível',error!),if(server.isEmpty)info(Icons.link,'Liga o Bennu','Definições → endereço do Core. No Android usa IP LAN ou HTTPS, nunca localhost.'),if(data!=null)GridView.count(crossAxisCount:2,shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),crossAxisSpacing:10,mainAxisSpacing:10,children:[metric('Agentes','${data!['agents']}',Icons.smart_toy),metric('Tarefas','${data!['tasks']}',Icons.task_alt),metric('Eventos','${ev.length}',Icons.bolt),metric('Core','ONLINE',Icons.public)]),const SizedBox(height:14),if(data!=null)info(Icons.bolt,'Atividade real',ev.isEmpty?'Sem eventos de auditoria.':ev.take(8).map((e)=>'${e['type']}: ${e['detail']??''}').join('\n')),const SizedBox(height:20),const Text('Módulos Bennu OS',style:TextStyle(fontSize:19,fontWeight:FontWeight.w900)),const SizedBox(height:10),GridView.count(crossAxisCount:2,shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),crossAxisSpacing:10,mainAxisSpacing:10,children:const[Tile(Icons.psychology,'IA & Agentes'),Tile(Icons.shield,'SOC Segurança'),Tile(Icons.business,'Business'),Tile(Icons.point_of_sale,'Vendas'),Tile(Icons.cloud,'Cloud'),Tile(Icons.code,'Developer'),Tile(Icons.storefront,'Marketplace'),Tile(Icons.auto_awesome,'Ghost Mode')]) ]));}
 Widget hero(bool online)=>Container(padding:const EdgeInsets.all(20),decoration:BoxDecoration(borderRadius:BorderRadius.circular(24),border:Border.all(color:orange.withValues(alpha:.3)),gradient:const LinearGradient(colors:[Color(0xFF171E28),Color(0xFF0E1219)])),child:Row(children:[const Icon(Icons.local_fire_department,color:orange,size:40),const SizedBox(width:14),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('BENNU COMMAND CENTER',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900)),Text(server.isEmpty?'PRIVATE • NÃO CONFIGURADO':online?'ONLINE • DADOS REAIS':'OFFLINE',style:TextStyle(color:server.isEmpty?Colors.orangeAccent:online?green:Colors.orangeAccent,fontWeight:FontWeight.w800)),if(server.isNotEmpty)Text(server,style:const TextStyle(color:muted,fontSize:10))])),if(server.isNotEmpty)IconButton(onPressed:busy?null:refresh,icon:busy?const SizedBox(width:18,height:18,child:CircularProgressIndicator(strokeWidth:2)):const Icon(Icons.refresh))]));
 Widget info(IconData i,String t,String x)=>Card(child:Padding(padding:const EdgeInsets.all(15),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(i,color:orange),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(t,style:const TextStyle(fontWeight:FontWeight.w800)),const SizedBox(height:5),Text(x,style:const TextStyle(color:muted,height:1.4))]))])));
 Widget metric(String t,String v,IconData i)=>Card(child:Padding(padding:const EdgeInsets.all(14),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(i,color:orange),const Spacer(),Text(t,style:const TextStyle(color:muted)),Text(v,style:const TextStyle(fontSize:20,fontWeight:FontWeight.w900)),const Text('REAL',style:TextStyle(color:green,fontSize:9))])));
 Widget agents()=>shell(Column(crossAxisAlignment:CrossAxisAlignment.start,children:[title('IA & Agentes','Agentes especializados'),for(final a in const['CEO','Comercial','Segurança','Programador','Financeiro','Marketing'])Card(margin:const EdgeInsets.only(bottom:9),child:ListTile(leading:const Icon(Icons.smart_toy,color:orange),title:Text('Agente $a',style:const TextStyle(fontWeight:FontWeight.w800)),trailing:const Text('PRONTO',style:TextStyle(color:green,fontSize:10,fontWeight:FontWeight.w800))))]));
 Widget missions()=>shell(Column(crossAxisAlignment:CrossAxisAlignment.start,children:[title('Missões','Mission Control'),info(Icons.track_changes,'Missões reais',data==null?'Liga o servidor para visualizar o estado operacional.':'O Core está ligado; tarefas e auditoria estão disponíveis.')]));
 Widget security()=>shell(Column(crossAxisAlignment:CrossAxisAlignment.start,children:[title('Segurança','SOC privado'),info(Icons.shield,'Postura','Ações de alto risco ficam protegidas por aprovação, RBAC e auditoria.'),const SizedBox(height:10),info(Icons.monitor_heart,'Telemetria',data==null?'Sem ligação ao Core.':'Core online; eventos reais disponíveis.') ]));
 Widget analytics()=>shell(Column(crossAxisAlignment:CrossAxisAlignment.start,children:[title('Analytics','Métricas reais'),data==null?info(Icons.query_stats,'Sem dados','Liga o servidor Bennu.'):dashboardCards()]));
 Widget dashboardCards(){final d=data!;return GridView.count(crossAxisCount:2,shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),crossAxisSpacing:10,mainAxisSpacing:10,children:[metric('Agentes','${d['agents']}',Icons.smart_toy),metric('Tarefas','${d['tasks']}',Icons.task_alt),metric('Eventos','${(d['events'] as List).length}',Icons.bolt),metric('Estado','ONLINE',Icons.public)]);}
 Widget settings()=>shell(Column(crossAxisAlignment:CrossAxisAlignment.start,children:[title('Definições','Ligação privada ao Bennu Core'),info(Icons.lock,'Servidor privado','Usa IP da LAN para desenvolvimento ou HTTPS para acesso remoto.'),const SizedBox(height:14),TextField(controller:url,keyboardType:TextInputType.url,decoration:const InputDecoration(labelText:'URL do Bennu Core',hintText:'http://192.168.1.50:8000')),const SizedBox(height:12),FilledButton.icon(onPressed:busy?null:save,icon:const Icon(Icons.save),label:const Text('Guardar e testar'))]));
 Widget title(String a,String b)=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(a,style:const TextStyle(fontSize:28,fontWeight:FontWeight.w900)),Text(b,style:const TextStyle(color:muted)),const SizedBox(height:20)]);
 @override Widget build(BuildContext c){final wide=MediaQuery.sizeOf(c).width>=850;return Scaffold(appBar:wide?null:AppBar(title:Text(names[tab],style:const TextStyle(fontWeight:FontWeight.w800))),body:wide?Row(children:[NavigationRail(selectedIndex:tab,onDestinationSelected:(v)=>setState(()=>tab=v),labelType:NavigationRailLabelType.all,leading:const Padding(padding:EdgeInsets.all(12),child:Icon(Icons.local_fire_department,color:orange,size:34)),destinations:[for(final n in names.take(10))NavigationRailDestination(icon:const Icon(Icons.circle_outlined),label:Text(n))]),const VerticalDivider(width:1),Expanded(child:page())]):page(),bottomNavigationBar:wide?null:NavigationBar(selectedIndex:tab.clamp(0,4),onDestinationSelected:(v)=>setState(()=>tab=v),destinations:[for(final n in names.take(5))NavigationDestination(icon:const Icon(Icons.circle_outlined),label:n)]);}
}
class Tile extends StatelessWidget{const Tile(this.i,this.t,{super.key});final IconData i;final String t;Widget build(BuildContext c)=>Card(child:Padding(padding:const EdgeInsets.all(15),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(i,color:Theme.of(c).colorScheme.primary),const Spacer(),Text(t,style:const TextStyle(fontWeight:FontWeight.w800))])));}
